receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # do noting
  debug:
  # send to jaeger
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  # send to zipkin
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans



service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,zipkin,debug]